### ISSUE TITLE
DTS update

### ISSUE THREAD

**Issue by vborchsh** [trabucayre/redpitaya#5]
Sorry for silly question, but:

How can I update the DTS files in conception of this repository? Imagine, I have DTS files, generated by Vivado/Vitis: pl.dtsi, pcw.dtsi, system-top.dts. How correctly connect them to the repository?

I tried with BR2_LINUX_KERNEL_CUSTOM_DTS_PATH but no luck - hang during booting.

Thanks!

**Comment by trabucayre** [comment]
By default, the **dts** file is stored as a patch. This one is applied by *buildroot* after unpack, and may be modified manually directly into kernel source tree (`arm/arm/boot/dts/zynq-red_pitaya.dts`).
It's true: `BR2_LINUX_KERNEL_CUSTOM_DTS_PATH` may be another way to use a **dts** file from somewhere, but I don't know if it deal correctly with **dtsi** + **dts**: maybe you have to try to merge all of them into one, monolythic, file.

Alternate way I use, with custom *gateware*, is to use *device tree overlay* approach to update in live (and temporary) the device tree in memory to add/modify/disable nodes.

Which modifications you have to apply? Is it *gateware* related?

**Comment by vborchsh** [comment]
Thank you for rapid answer!

I'm trying to connect to PS two cores: AXI Quad SPI and AXI IIC. The cores placed in PL part. Obviously, I have to modify the DTS files to support this core in Linux.

I would also prefer DTS overlay, but I never tried it. And it looks a bit complex for me. Is there any example in this repository?

Is DTS overlay makes able to interact with Kernel space drivers such a IIC and SPI drivers from Xilinx?

Thanks.

**Comment by trabucayre** [comment]
Ok I see.
> 
> I would also prefer DTS overlay, but I never tried it. And it looks a bit complex for me. Is there any example in this repository?

Not in this repository but you can read this [dts](https://github.com/oscimp/oscimpDigital/blob/master/doc/tutorials/redpitaya/3-PLPS/app/tutorial3.dts) and [this section](https://github.com/oscimp/oscimpDigital/tree/master/doc/tutorials/redpitaya/3-PLPS#devicetree-overlay) about this topic
> 
> Is DTS overlay makes able to interact with Kernel space drivers such a IIC and SPI drivers from Xilinx?

Yes of course: it is uses to inform the kernel to the need to probe one or more drivers, it has exactly the same role as default dts but allows to update devicetree without having to generate a new dtb and to reboot the board.

**Comment by vborchsh** [comment]
Ok, many thanks! I think, we can close the issue.

**Comment by trabucayre** [comment]
I close it. Feel free to reopen, or create new issue if required

**Comment by vborchsh** [comment]
Just to clarify for possible users:

Replacing device tree in patches by providing BR2_LINUX_KERNEL_CUSTOM_DTS_PATH works pretty fine with the repository's conception.
